### Create a new user
POST http://localhost:3000/user
content-type: application/json

{
  "name": "Georgie Cucumber",
  "email": "test123@test.com",
  "password": "12345"
}

### Find a particular user with a given ID
GET http://localhost:3000/user?1dde8337-0ab4-4c71-a8f4-a5a344b7c1f5

### Find all users
GET http://localhost:3000/user

### Delete a user given id
DELETE http://localhost:3000/user?1dde8337-0ab4-4c71-a8f4-a5a344b7c1f5

### Update a user
PATCH http://localhost:3000/user?1dde8337-0ab4-4c71-a8f4-a5a344b7c1f5
content-type: application/json

{
  "password": "aaaaa"
}